name: build

on:
  repository_dispatch:
    types: [build-on-demand]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.18.1'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'Xhofe/alist'
          path: alist
          fetch-depth: 0

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: patch

      - name: Patch (part 1)
        run: |
          mv -f patch/*.go alist/cmd
          mv patch/alist.syso alist
          cat patch/go.mod.patch >> alist/go.mod
          sed -i 's/0\.0\.0\.0/127\.0\.0\.1/g' alist/internal/conf/config.go
          sed -i 's/linux-musl-amd64 linux-musl-arm64//g' alist/build.sh
          sed -i 's/windows\/amd64,darwin\/amd64/windows\/amd64/g' alist/build.sh
          sed -i 's/-w -s/-w -s -H windowsgui/g' alist/build.sh
          sed -i 's/upx -9/upx -9 -vf --lzma --compress-icons=0/g' alist/build.sh
          sed -i 's/alist-windows-amd64.exe/alist-windows*.exe/g' alist/build.sh
          cd alist
          go mod tidy
          echo "version=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
          cd ..
          
      - name: Patch (part 2)
        run: |
          sed -i 's/version="dev"/version="${{ env.version }}-dev"/g' alist/build.sh

      - name: Install dependencies
        run: |
          docker pull techknowlogick/xgo:latest
          go install src.techknowlogick.com/xgo@latest
          sudo apt install upx

      - name: Build
        run: |
          cd alist
          bash build.sh dev

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.version }}-win
          path: alist/dist
