name: build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [1.18.1]
    name: Build
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'Xhofe/alist'
          path: alist

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: patch

      - name: Patch
        run: |
          mv -f patch/alist.go alist
          mv patch/alist.syso alist
          cat patch/go.mod.patch >> alist/go.mod
          sed -i 's/linux\/amd64,windows\/amd64,darwin\/amd64/windows\/arm64/g' alist/build.sh
          sed -i 's/-w -s/-w -s -H windowsgui/g' alist/build.sh
          cd alist
          go mod tidy
          cd ..

      - name: Install dependencies
        run: |
          docker pull techknowlogick/xgo:latest
          go install src.techknowlogick.com/xgo@latest
          sudo apt install upx
      - name: Build
        run: |
          mv alist/build.sh .
          bash build.sh web
          mv dist/* alist/public
          bash build.sh build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: alist/build
